export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_BYNAME="GETBYNAME";
export const GET_DETAIL="GET_DETAIL";
export const GET_ACTIVITIES="GET_ACTIVITIES";
export const POST_ACTIVITIES="POST_ACTIVITIES";
export const ORDER_COUNTRIES="ORDER_COUNTRIES";
export const ORDER_POPULATION="ORDER_POPULATION";





