export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_BYNAME="GETBYNAME";
export const GET_BYID="GET_BYID";
export const POST_ACTIVITY="POST_ACTIVITY";
export const GET_ACTIVITIES="GET_ACTIVITIES";
export const ORDER_COUNTRIES="ORDER_COUNTRIES";
export const ORDER_POPULATION="ORDER_POPULATION";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";




